w4/w4d3/NinetyNineCats/config/routes.rb
NinetyNineCatsDay1::Application.routes.draw do
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:create, :new, :destroy]

  root to: redirect("/cats")
end

w4/w4d3/NinetyNineCats/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  user_name       :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#

class User < ActiveRecord::Base
   #is this going to work?
  validates :user_name, presence: true, uniqueness: true
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6,  allow_nil: true}

  has_many :cats,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: "Cat"

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.update(session_token: self.session_token)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def is_password?(password)
     BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    if user && user.is_password?(password)
      return user
    else
      return nil
    end
  end

  def password
    @password
  end
end

w4/w4d3/NinetyNineCats/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logout, only: :new
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    #fail
    #@user.password = @user.password
    login_user!
    #fail
    if @user.save
      redirect_to cats_url
    else
      flash.now[:errors] = @user.errors.full_messages
      session[:session_token] = nil
      render :new
    end
  end


  private
  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

w4/w4d3/NinetyNineCats/app/helpers/users_helper.rb
module UsersHelper
end

w4/w4d3/NinetyNineCats/app/views/users/new.html.erb
<h1>Make New Account</h1>
<%= render "shared/errors" %>
<form action="<%= users_url %>" method="post">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

  <label for="user[user_name]">User Name:</label><br>
  <input id="user[user_name]" type="text" name="user[user_name]", value= "<%=@user.user_name %>" />
  <br>
  <label for="user[password]">Password:</label><br>
  <input id="user[password]" type="password" name="user[password]", value= "<%=@user.password %>" />

  <br>

  <input type="submit" value="Submit!" />
</form>